### ISSUE TITLE
Circular dependency between klampt.model.trajectory and klampt.control.robotinterfaceutils

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/Klampt#135]
Testing on 0.9 branch.

When I try to use latest version of `klampt_control`, the error message indicate there could be a circular dependency issue. 
In `klampt/io/loader.py`,  
`from ..model.trajectory import Trajectory,HermiteTrajectory,SO3Trajectory,SE3Trajectory`
In `klampt/model/trajectory.py`,
`from ..control.robotinterface import RobotInterfaceBase`
In `klampt/control/__init__.py`,
`from .robotinterfaceutils import StepContext,RobotInterfaceCompleter,OmniRobotInterface`
In `klampt/control/robotinterfaceutils.py`,
`from ..model.trajectory import Trajectory,HermiteTrajectory`
where `..model.trajectory` is partially initialized.

I also attached the whole error message:

Traceback (most recent call last):
  File "/usr/local/bin/klampt_control", line 11, in <module>
    load_entry_point('Klampt==0.9.0', 'console_scripts', 'klampt_control')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/apps/klampt_control.py", line 1, in <module>
    from klampt import *
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/io/__init__.py", line 1, in <module>
    from .loader import load,save,write,read,to_json,from_json
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/io/loader.py", line 69, in <module>
    from ..model.trajectory import Trajectory,HermiteTrajectory,SO3Trajectory,SE3Trajectory
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/model/trajectory.py", line 11, in <module>
    from ..control.robotinterface import RobotInterfaceBase
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/__init__.py", line 3, in <module>
    from .robotinterfaceutils import StepContext,RobotInterfaceCompleter,OmniRobotInterface
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 56, in <module>
    from ..model.trajectory import Trajectory,HermiteTrajectory
ImportError: cannot import name 'Trajectory' from partially initialized module 'klampt.model.trajectory' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/model/trajectory.py)

**Comment by krishauser** [comment]
Fixed with latest push.
