### ISSUE TITLE
cannot use control mode setPiecewiseCubic for gripper joint

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/Klampt#137]
Testing on branch 0.9.

When I run `klampt_control ur5_with_robotiq85_sim.json` for `Klampt-examples` and set gripper joint position using panel, this is an error in `_JointInterfaceEmulatorData.getCommand`.

The control mode for gripper joint was promoted to `setPiecewiseCubic` and `trajectoryTimes` is set to `[0]`. However, when `getCommand` is called again in `_try_methods`, an error occurs because `trajectoryTimes` is `None` for `_JointInterfaceEmulatorData`. 

I attached the complete error message:
Exception raised while evaluating argument of method setPiecewiseCubic of object StatefulWrapper(KinematicSimControlInterface)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/apps/klampt_control.py", line 50, in __exit__
    self.gui.controller.endStep()
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 2347, in endStep
    (desiredControlMode,baseControlMode) = self._emulator.sendToInterface(iface,inds)
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 4324, in sendToInterface
    res=_try_methods(interface,['setPiecewiseLinear','setPiecewiseCubic','setPID','setPosition','setVelocity','moveToPosition','setTorque'],
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 851, in _try_methods
    a = a()
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 4327, in <lambda>
    lambda:self.getCommand('setPiecewiseCubic',indices),
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 4458, in getCommand
    res = [j.getCommand(commandType) for j in activeJoints]
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 4458, in <listcomp>
    res = [j.getCommand(commandType) for j in activeJoints]
  File "/usr/local/lib/python3.8/dist-packages/Klampt-0.9.0-py3.8-linux-x86_64.egg/klampt/control/robotinterfaceutils.py", line 3784, in getCommand
    assert self.trajectoryTimes is not None,"Can't get piecewise cubic trajectory except in piecewise cubic mode"
AssertionError: Can't get piecewise cubic trajectory except in piecewise cubic mode
addError Exception on endStep: Can't get piecewise cubic trajectory except in piecewise cubic mode

**Comment by krishauser** [comment]
Should be fixed with latest commit
