### ISSUE TITLE
ImportError: cannot import name 'fit_plane_centroid' from 'klampt.model.sensing'

### ISSUE THREAD

**Issue by qwasko1212** [krishauser/Klampt#139]
I would like to automatically zoom out a scene to see a robot properly. When I am using the method `vis.autoFitCamera(rotate=False)` it generates an exception:

```
klampt.vis: auto-fitting camera to scene.
/home/okv/Documents/projects/prj/venv/lib/python3.8/site-packages/klampt/vis/visualization.py:3818: UserWarning: Unable to auto-fit camera
  warnings.warn("Unable to auto-fit camera")
Traceback (most recent call last):
  File "/home/okv/Documents/projects/prj/venv/lib/python3.8/site-packages/klampt/vis/visualization.py", line 3814, in autoFitCamera
    autoFitViewport(vp,list(self.items.values()),zoom=zoom,rotate=rotate)
  File "/home/okv/Documents/projects/prj/venv/lib/python3.8/site-packages/klampt/vis/visualization.py", line 1498, in autoFitViewport
    from ..model.sensing import fit_plane_centroid
ImportError: cannot import name 'fit_plane_centroid' from 'klampt.model.sensing' (/home/okv/Documents/projects/prj/venv/lib/python3.8/site-packages/klampt/model/sensing.py)
```

As a dirty fix, I had to comment `from ..model.sensing import fit_plane_centroid` because I am anyway not using the rotation functionality. 

Can this bug be fixed?

**Comment by krishauser** [comment]
Fixed in master!
