### ISSUE TITLE
failed run the demo - klampt_control Klampt-examples/robotinfo/ur5/ur5_sim.py

### ISSUE THREAD

**Issue by sunnymints** [krishauser/Klampt#197]
when i run 
`klampt_control Klampt-examples/robotinfo/ur5/ur5_sim.py`

it will show：
`***  klampt.vis: using Qt5 as the visualization backend  ***
klampt_control: a GUI to control a Klamp't Robot Interface Layer (RIL) robot

Unable to load module ur5_sim.py in any of Klampt-examples/robotinfo/ur5 +s []
Traceback (most recent call last):
  File "/home/jixiancheng/.local/bin/klampt_control", line 8, in <module>
    sys.exit(main())
  File "/home/jixiancheng/.local/lib/python3.8/site-packages/klampt/apps/klampt_control.py", line 1331, in main
    controller = info.controller()
  File "/home/jixiancheng/.local/lib/python3.8/site-packages/klampt/model/robotinfo.py", line 267, in controller
    mod = _dynamic_load_module(self.controllerFile,self.filePaths)
  File "/home/jixiancheng/.local/lib/python3.8/site-packages/klampt/model/robotinfo.py", line 1111, in _dynamic_load_module
    raise exc
TypeError: exceptions must derive from BaseException
`
note：
I installed the klampt by source following https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Install-Linux.md.
I completed all the steps in the document and can run `bin/SimTest Klampt-examples/data/athlete_fractal_1.xml` 
but I get an error when running `sudo make python-install`.

`~/Klampt$ sudo make python-install`

`make: *** There are no rules for making goals“python-install”/ stop.`

I don’t know if this is the reason for the problem in this title.

**Comment by krishauser** [comment]
It looks like you have a Python install already. You can try pip installing via "pip install ." within Klampt/Python.

The example works for me, but perhaps it was a more recent upgrade. Could you try with klampt version 0.10+?
