### ISSUE TITLE
Import error when using klampt.sim.batch.doSim

### ISSUE THREAD

**Issue by dwjoris** [krishauser/Klampt#69]
I am using klampt in Python2.7 and installed it with pip. When using the function klampt.sim.batch.doSim, I get the following import error:

Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from Simulator import Simulator
  File "/home/joris/klampt/my_code/SimulationTrainer/Simulator.py", line 2, in <module>
    from klampt.sim import batch
  File "/home/joris/.local/lib/python2.7/site-packages/klampt/sim/batch.py", line 2, in <module>
    from ..model import map
ImportError: cannot import name map

Am I missing some additional packages?
Thank you!

**Comment by krishauser** [comment]
This is odd, the most recent versions have renamed the "map" module to "access" in order to not conflict with the Python keyword. Perhaps you could open up /home/joris/.local/lib/python2.7/site-packages/klampt/sim/batch.py and do a find-replace?
